export const initialData = [
        {
            "id": 5367,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5366,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5365,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5364,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5362,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5361,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5360,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5359,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5358,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Сделай заказ!\r\n\r\nОформи заказ воды 19л всего за 150 рублей!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:57:42",
            "updated_at": "2020-06-15 06:57:42",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5357,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:33",
            "updated_at": "2020-06-15 06:52:33",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5356,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:33",
            "updated_at": "2020-06-15 06:52:33",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5355,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:33",
            "updated_at": "2020-06-15 06:52:33",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5354,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:32",
            "updated_at": "2020-06-15 06:52:32",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5352,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:32",
            "updated_at": "2020-06-15 06:52:32",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5351,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:32",
            "updated_at": "2020-06-15 06:52:32",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5350,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:32",
            "updated_at": "2020-06-15 06:52:32",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5349,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:32",
            "updated_at": "2020-06-15 06:52:32",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 5348,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест\r\n\r\nТест_на_картиночку",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-06-15 06:52:32",
            "updated_at": "2020-06-15 06:52:32",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 4932,
            "group_id": 12,
            "user_id": 12233,
            "type": "message",
            "message": "Мы здесь проводим тестирование",
            "active": true,
            "is_system_message": false,
            "created_at": "2020-06-05 12:45:18",
            "updated_at": "2020-06-05 12:45:18",
            "user": {
                "id": 12233,
                "username": "Original test",
                "email": "test@test.ru",
                "phone": "9999999997",
                "phone_number": "+79999999997",
                "contract_number": 20298,
                "type": 1,
                "role": "customer",
                "legal_address": null,
                "tax_individual_number": "",
                "registration_reason_code": "",
                "bank_id": "",
                "bank_name": "",
                "correspondent_account": "",
                "checking_account": "",
                "invite_code": "vfmFV65I#20298",
                "city_id": 1
            },
            "is_not_client_message": false
        },
        {
            "id": 2809,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!!\r\n\r\nСкажите \"Пельмешка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:57:06",
            "updated_at": "2020-05-08 07:57:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2806,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!!\r\n\r\nСкажите \"Пельмешка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:57:06",
            "updated_at": "2020-05-08 07:57:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2805,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!!\r\n\r\nСкажите \"Пельмешка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:57:06",
            "updated_at": "2020-05-08 07:57:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2804,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!!\r\n\r\nСкажите \"Пельмешка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:57:06",
            "updated_at": "2020-05-08 07:57:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2803,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!!\r\n\r\nСкажите \"Пельмешка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:57:06",
            "updated_at": "2020-05-08 07:57:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2802,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!!\r\n\r\nСкажите \"Пельмешка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:57:06",
            "updated_at": "2020-05-08 07:57:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2801,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!!\r\n\r\nСкажите \"Пельмешка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:57:06",
            "updated_at": "2020-05-08 07:57:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2800,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!\r\n\r\nСкажите \"Макарошка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:49:04",
            "updated_at": "2020-05-08 07:49:04",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2797,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!\r\n\r\nСкажите \"Макарошка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:49:04",
            "updated_at": "2020-05-08 07:49:04",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2796,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!\r\n\r\nСкажите \"Макарошка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:49:04",
            "updated_at": "2020-05-08 07:49:04",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2795,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!\r\n\r\nСкажите \"Макарошка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:49:04",
            "updated_at": "2020-05-08 07:49:04",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2794,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!\r\n\r\nСкажите \"Макарошка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:49:04",
            "updated_at": "2020-05-08 07:49:04",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2793,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!\r\n\r\nСкажите \"Макарошка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:49:04",
            "updated_at": "2020-05-08 07:49:04",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2792,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Доброе утро, это тест!\r\n\r\nСкажите \"Макарошка\", если пуш до вас дошел!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-08 07:49:04",
            "updated_at": "2020-05-08 07:49:04",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2789,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2788,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2787,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2786,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2785,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2784,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2783,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2782,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 2781,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Тест get-ссылки\r\n\r\nОбновляйте приложение и получайте доступ к свежим акциям и функциям прямо сейчас!\r\nhttps://kronvoda.app11.ru/get/",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-05-07 07:34:06",
            "updated_at": "2020-05-07 07:34:06",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 399,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Заказ №51472 доставлен\r\n\r\nПожалуйста, оцените работу службы доставки",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-03-17 23:58:05",
            "updated_at": "2020-03-17 23:58:05",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 389,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Заказ №51422 доставлен\r\n\r\nПожалуйста, оцените работу службы доставки",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-03-12 17:53:04",
            "updated_at": "2020-03-12 17:53:04",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 387,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Заказ №51425 доставлен\r\n\r\nПожалуйста, оцените работу службы доставки",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-03-10 08:47:14",
            "updated_at": "2020-03-10 08:47:14",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 384,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Для 123\r\n\r\nЗайди в приложение и купи воды, ну!!!!!",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-03-06 09:01:45",
            "updated_at": "2020-03-06 09:01:45",
            "user": null,
            "is_not_client_message": true
        },
        {
            "id": 383,
            "group_id": 12,
            "user_id": 12393,
            "type": "message",
            "message": "Ну извините",
            "active": true,
            "is_system_message": false,
            "created_at": "2020-03-06 06:11:24",
            "updated_at": "2020-03-06 06:11:24",
            "user": {
                "id": 12393,
                "username": "Ирина_менеджер_проектов",
                "email": "irina.aquadelivery@gmail.com",
                "phone": null,
                "phone_number": null,
                "contract_number": null,
                "type": 1,
                "role": "admin",
                "legal_address": null,
                "tax_individual_number": null,
                "registration_reason_code": null,
                "bank_id": null,
                "bank_name": null,
                "correspondent_account": null,
                "checking_account": null,
                "invite_code": null,
                "city_id": 1
            },
            "is_not_client_message": true
        },
        {
            "id": 382,
            "group_id": 12,
            "user_id": 12393,
            "type": "message",
            "message": "Здравствуйте, курьер уже везёт ваш заказ, простите за задержку",
            "active": true,
            "is_system_message": false,
            "created_at": "2020-03-06 06:10:27",
            "updated_at": "2020-03-06 06:10:27",
            "user": {
                "id": 12393,
                "username": "Ирина_менеджер_проектов",
                "email": "irina.aquadelivery@gmail.com",
                "phone": null,
                "phone_number": null,
                "contract_number": null,
                "type": 1,
                "role": "admin",
                "legal_address": null,
                "tax_individual_number": null,
                "registration_reason_code": null,
                "bank_id": null,
                "bank_name": null,
                "correspondent_account": null,
                "checking_account": null,
                "invite_code": null,
                "city_id": 1
            },
            "is_not_client_message": true
        },
        {
            "id": 381,
            "group_id": 12,
            "user_id": 12233,
            "type": "message",
            "message": "11111",
            "active": true,
            "is_system_message": false,
            "created_at": "2020-03-06 06:10:11",
            "updated_at": "2020-03-06 06:10:11",
            "user": {
                "id": 12233,
                "username": "Original test",
                "email": "test@test.ru",
                "phone": "9999999997",
                "phone_number": "+79999999997",
                "contract_number": 20298,
                "type": 1,
                "role": "customer",
                "legal_address": null,
                "tax_individual_number": "",
                "registration_reason_code": "",
                "bank_id": "",
                "bank_name": "",
                "correspondent_account": "",
                "checking_account": "",
                "invite_code": "vfmFV65I#20298",
                "city_id": 1
            },
            "is_not_client_message": false
        },
        {
            "id": 380,
            "group_id": 12,
            "user_id": null,
            "type": "notification",
            "message": "Заказ №51420 доставлен\r\n\r\nПожалуйста, оцените работу службы доставки",
            "active": true,
            "is_system_message": true,
            "created_at": "2020-03-06 06:08:04",
            "updated_at": "2020-03-06 06:08:04",
            "user": null,
            "is_not_client_message": true
        }
    ]
